default:
  deploy:
    root: 'public'
    hostname: 'fishtag.ru'
    destination: '/home/fishtag/data/www/tmp'
    shell: 'ssh'
  production:
    tasks:
      - bower
      - bower-packages
      - coffee
      - fonts
      - slimRender
      - htmlInclude
      - iconsfont
      - images
      - sounds
      - sprite
      - styles
      - vendor
  html:
    slim:
      pretty: true
    include:
      prefix: '##'
      basepath: '@file'
    beautifier:
      indentSize: 2
      wrapLineLength: 80
      preserveNewlines: true
  block:
    styles:
      include: ./app/scss/application.scss
      target: ./app/scss/includes
      template: ./gulp/templates/_block.scss
    slim:
      include: ./app/slim/index.slim
      target: ./app/slim/include
      template: ./gulp/templates/block.slim