default:
  livereload:
    express_port: 4000
    livereload_port: 35729
  html:
    slim:
      pretty: true
    include:
      prefix: '##'
      basepath: '@file'
    beautifier:
      indentSize: 2
      wrapLineLength: 80
      preserveNewlines: true
  block:
    styles:
      include: ./app/scss/application.scss
      target: ./app/scss/includes
      template: ./gulp/templates/_block.scss
    slim:
      include: ./app/slim/index.slim
      target: ./app/slim/include
      template: ./gulp/templates/block.slim