default:
  deploy:
    ftp:
      host: 'localhost'
      user: 'username'
      password: 'password'
      parallel: 10
      remotePath: ''
    rsync:
      root: 'public'
      hostname: 'localhost'
      destination: '/home/'
      recursive: true
      clean: true
      shell: 'ssh'
  production:
    tasks:
      - bower
      - bower-packages
      - coffee
      - fonts
      - slimRender
      - htmlInclude
      - iconsfont
      - images
      - sounds
      - sprite
      - sass
      - css-import
      - vendor
  html:
    slim:
      pretty: true
      include: true
      options:
        - encoding='utf-8'
        - include_dirs=['app/slim/']
    include:
      prefix: '##'
      basepath: '@file'
    beautifier:
      indentSize: 2
      wrapLineLength: 80
      preserveNewlines: true
  block:
    styles:
      include: ./app/scss/application.scss
      target: ./app/scss/includes
      template: ./gulp/templates/_block.scss
    slim:
      include: ./app/slim/index.slim
      target: ./app/slim/include
      template: ./gulp/templates/block.slim